// Builds the Material Symbols pack: one variable font for the assembly to embed, and the C# name constants
// beside it. Rounded only — the rounded terminals are what sit next to Lucide without reading as a second
// design; sharp and outlined-the-style are a different decision, not a different flag.
//
// Why a font and not the SVGs it used to pack — the owner's call, 2026-09-02. A glyph drawn as a CSS mask is
// rasterised by the image path; the same glyph in a font goes through the text rasteriser, and at 14 and 16
// pixels the difference is plain. Two things follow from it, and both are worth more than the change cost:
//
//   - `FILL` stays an axis, so the filled and outlined drawings stop being two 700 KB tables and become one
//     declaration on one file;
//   - `opsz` stays an axis, so a 14px icon is drawn by the optical size made for small sizes rather than by a
//     24px drawing shrunk. `font-optical-sizing: auto` is the CSS default, so nothing has to ask for it.
//
// `wght` and `GRAD` are pinned instead, because a UI never asks for either: that is what takes the file from
// 5.3 MB to 382 KB while keeping every one of the 3 899 glyphs.

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import subsetFont from "subset-font";

const SOURCE = "node_modules/material-symbols/material-symbols-rounded.woff2";
const NAME_SOURCE = "node_modules/material-symbols/index.d.ts";
const DIST = "dist";
const FONT = "ui-icons-material.woff2";
const NAMES = "../../NE.Standard.UI.Icons.Material/MaterialIcons.cs";

// Reserved words a glyph name would collide with as a C# identifier, plus the one name that starts with a
// digit. Everything else PascalCases cleanly.
const RESERVED = new Set(["Class", "Object", "String", "Double", "Switch", "Lock", "Default", "Event", "Base", "Checked", "Void"]);

function toIdentifier(name) {
    const pascal = name
        .split(/[_-]+/)
        .filter(part => part.length > 0)
        .map(part => part[0].toUpperCase() + part.slice(1))
        .join("");

    const safe = /^[0-9]/.test(pascal) ? "N" + pascal : pascal;

    return RESERVED.has(safe) ? safe + "Icon" : safe;
}

// The package's own type declaration is the glyph list, which keeps the names and the font in step by
// construction — they ship together and are generated from the same source.
function readNames() {
    const names = readFileSync(NAME_SOURCE, "utf8")
        .split("\n")
        .map(line => line.trim().match(/^"([a-z0-9_]+)",?$/))
        .filter(match => match !== null)
        .map(match => match[1]);

    if (names.length === 0)
        throw new Error(`No glyph names were found in ${NAME_SOURCE}.`);

    return names.sort();
}

const names = readNames();

// Subsetting to every name is what drops the parts of the file a UI never reaches — and it is also what keeps
// the ligature lookups for exactly these names, which is how a glyph is addressed at all.
const font = await subsetFont(readFileSync(SOURCE), names.join(" "), {
    targetFormat: "woff2",
    variationAxes: { wght: 400, GRAD: 0 }
});

mkdirSync(DIST, { recursive: true });
writeFileSync(resolve(DIST, FONT), font);

console.log(`font: ${names.length} glyphs, ${(font.length / 1024).toFixed(0)} KB`);

// One constant per glyph, and the style is the application's choice rather than the icon's: both drawings are
// the same name, told apart by a suffix that becomes a value on the FILL axis.
const seen = new Map();
const lines = [];

for (const name of names) {
    const identifier = toIdentifier(name);

    if (seen.has(identifier))
        throw new Error(`Identifier '${identifier}' is produced by both '${seen.get(identifier)}' and '${name}'.`);

    seen.set(identifier, name);
    lines.push(`    public const string ${identifier} = "ms-${name.replaceAll("_", "-")}";`);
}

const source = `// <auto-generated />
// Built by Client/scripts/build-icons.mjs from material-symbols. Do not edit by hand.

namespace NE.Standard.UI.Icons.Material;

/// <summary>
/// Every Material Symbols name, as the string an <c>Icon</c> property takes. The <c>ms-</c> prefix is part
/// of the value: a glyph class is global, and Material and Lucide share a hundred names between them.
/// Which of these a page can actually draw is what the application registers — see <c>AddMaterialWebIcons</c>.
/// <para>
/// Partial: the outlined drawing of any of these is the same name plus a suffix, and that half is written by
/// hand in MaterialIconStyles.cs.
/// </para>
/// </summary>
public static partial class MaterialIcons
{
${lines.join("\n")}
}
`;

writeFileSync(resolve(NAMES), source, "utf8");
console.log(`names: ${lines.length} constants`);
