// Builds the Material Symbols pack: one variable font for the assembly to embed, and the C# name constants
// beside it. Rounded only, the drawing family the framework's own marks are cut from.
//
// A font, not SVGs: the same glyph rasterises through the sharper text path instead of the image path at
// 14-16px. Keeping `FILL` and `opsz` as font axes serves the outlined drawing and small-size rendering from
// one file instead of separate 700 KB tables.
//
// `wght` and `GRAD` are pinned, since a UI never varies either — that takes the file from 5.3 MB to 386 KB
// while keeping all 3 927 glyphs.

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import subsetFont from "subset-font";

const SOURCE = "node_modules/material-symbols/material-symbols-rounded.woff2";
const NAME_SOURCE = "node_modules/material-symbols/index.d.ts";
const DIST = "dist";
const FONT = "ui-icons-material.woff2";
const NAMES = "../../NE.Standard.UI.Icons.Material/MaterialIcons.cs";

// Reserved words a glyph name would collide with as a C# identifier; a name that starts with a digit takes an `N`
// in toIdentifier. Everything else PascalCases cleanly.
const RESERVED = new Set(["Class", "Object", "String", "Double", "Switch", "Lock", "Default", "Event", "Base", "Checked", "Void"]);

function toIdentifier(name) {
    const pascal = name
        .split(/[_-]+/)
        .filter(part => part.length > 0)
        .map(part => part[0].toUpperCase() + part.slice(1))
        .join("");

    const safe = /^[0-9]/.test(pascal) ? "N" + pascal : pascal;

    return RESERVED.has(safe) ? safe + "Icon" : safe;
}

// The package's own type declaration is the glyph list, keeping names and font in step by construction —
// both ship together from the same source.
function readNames() {
    const names = readFileSync(NAME_SOURCE, "utf8")
        .split("\n")
        .map(line => line.trim().match(/^"([a-z0-9_]+)",?$/))
        .filter(match => match !== null)
        .map(match => match[1]);

    if (names.length === 0)
        throw new Error(`No glyph names were found in ${NAME_SOURCE}.`);

    return names.sort();
}

const names = readNames();

// Subsetting to every name drops the parts of the file a UI never reaches, while keeping the ligature lookups
// for exactly these names — which is how a glyph is addressed at all.
const font = await subsetFont(readFileSync(SOURCE), names.join(" "), {
    targetFormat: "woff2",
    variationAxes: { wght: 400, GRAD: 0 }
});

mkdirSync(DIST, { recursive: true });
writeFileSync(resolve(DIST, FONT), font);

console.log(`font: ${names.length} glyphs, ${(font.length / 1024).toFixed(0)} KB`);

// One constant per glyph; the style is the application's choice, not the icon's — both drawings share a name,
// told apart by a suffix mapped to the FILL axis.
const seen = new Map();
const lines = [];

for (const name of names) {
    const identifier = toIdentifier(name);

    if (seen.has(identifier))
        throw new Error(`Identifier '${identifier}' is produced by both '${seen.get(identifier)}' and '${name}'.`);

    seen.set(identifier, name);
    lines.push(`    public const string ${identifier} = "ms-${name.replaceAll("_", "-")}";`);
}

const source = `// <auto-generated />
// Built by Client/scripts/build-icons.mjs from material-symbols. Do not edit by hand.

namespace NE.Standard.UI.Icons.Material;

/// <summary>
/// Every Material Symbols name, as the string an <c>Icon</c> property takes — the <c>ms-</c> prefix is part of
/// the value, keeping a glyph class apart from the framework's <c>ne-</c> marks and an application's own classes.
/// Which of these a page can draw is what the application registers; see <c>AddMaterialWebIcons</c>.
/// <para>
/// Partial: the outlined drawing of any of these is the same name plus a suffix, written by hand in
/// MaterialIconStyles.cs.
/// </para>
/// </summary>
public static partial class MaterialIcons
{
${lines.join("\n")}
}
`;

writeFileSync(resolve(NAMES), source, "utf8");
console.log(`names: ${lines.length} constants`);
